[package]
name = "rust_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "server_tcp"
path = "./rust/server_tcp.rs"

[[bin]]
name = "server_udp"
path = "./rust/server_udp.rs"

[dependencies]
